##crest (v.1.3.0)
#Installations des packages et librairies utilisées 
library(devtools)
library(DBI)
library(RSQLite)
library(odbc)
if(!require(devtools)) install.packages("devtools")
#devtools::install_version("crestr", version = "1.2.0", repos = "https://cran.us.r-project.org")
devtools::install_github("mchevalier2/crestr",force=TRUE)
#dbDownload(dbname='gbif4crest_02')
con <- dbConnect(drv=RSQLite::SQLite(), dbname="gbif4crest_02-5min.sqlite3")
str(con)
print(dbListTables(con))
print(con)
library(crestr)
getTaxonomy(genus='Quercus',dbname="gbif4crest_02-5min.sqlite3")


#Fonction Crest pour produire des pseudo-données et fournie certains paramètres 
crest_ex<-read.csv2("popil_Data.csv",sep=';',dec=',')
crest_pse<-read.csv2("proxy_species_equivalency.csv",sep=';')
crest_exb<-read.csv2("LGP_Beaulieu2.csv",sep=';',dec=',')
crest_pseb<-read.csv2("proxy_species_equivalency2.csv",sep=';')
crest_exc<-read.csv2("LGP_Beaulieu3.csv",sep=';',dec=',')
crest_psec<-read.csv2("proxy_species_equivalency3.csv",sep=';')
str(crest_ex)
str(crest_pse)
#dbSubset(dbname='gbif4crest_02',taxaType=1,out='path/to/dbsubset')
print(crest_ex)
print(crest_pse)
#site_info=c(47.81,6.51)
rcnstrct<-crest.get_modern_data(df=crest_ex,climateWithObs=TRUE,pse=crest_pse,taxaType=1,climate=c('bio1','bio12'),realms='Palaearctic',minGridCells=15,dbname='gbif4crest_02-5min.sqlite3',verbose=TRUE)
recon<-crest.calibrate(rcnstrct,shape=c('normal','lognormal'),geoWeighting=TRUE,climateSpaceWeighting=TRUE,bin_width =c(2,100),npoints=500,verbose=TRUE)
plot(recon)
plot_climateSpace(recon)
plot_scatterPDFs(recon,xlim=c(-25,30),ylim=c(0,2000),filename='FigureScatter',uncertainties = 0.5)
plot_violinPDFs(recon,filename='FigureViolin.png')
plot_taxaCharacteristics(recon,taxanames='juniperus')
r<-loo(recon)
print(low)
plot_diagram(recon)
recon<-crest.reconstruct(recon,taxWeight='normalisation',presenceThreshold=0,uncertainties = c(0.5, 0.95),skip_for_loo = FALSE,verbose=TRUE)
plot(recon, climate = 'bio1')
plot(recon, climate = 'bio12')
plot(recon,simplify =FALSE)
plot_combinedPDFs(recon,samples=c(1),climate='bio1',only.present=TRUE,only.selected=FALSE)
plot_low(recon)
#Exportation des données
export(recon, dataname='final_reconGP_11Cas',fullUncertainties = FALSE,pdfs=FALSE)
