##crest (v.1.3.0)
#Installations des packages et librairies utilisées 
library(devtools)
library(DBI)
if(!require(devtools)) install.packages("devtools")
#devtools::install_version("crestr", version = "1.2.0", repos = "https://cran.us.r-project.org")
devtools::install_github("mchevalier2/crestr",force=TRUE)
#dbDownload(dbname='gbif4crest_02')
library(crestr)
getTaxonomy(genus='Spinacia',depth.out=6)


#Fonction Crest pour produire des pseudo-données et fournie certains paramètres 
crest_ex<-read.csv2("popil_Data.csv",sep=';')
crest_pse<-read.csv2("proxy_species_equivalency.csv",sep=';')
#dbSubset(dbname='gbif4crest_02',taxaType=1,out='path/to/dbsubset')
print(crest_ex)
print(crest_pse)
rcnstrct<-crest.get_modern_data(df=crest_ex, pse=crest_pse,taxaType=1,climate=c('bio1','bio12'),xmn=0,xmx=120,ymn=60,ymx=90,continents='Europe',minGridCells=20,site_info=c(47.81,6.51),dbname="gbif4crest_02",verbose='TRUE')
recon<-crest.calibrate(rcnstrct,shape=c('normal','lognormal'),bin_width =c(2,150),npoints=500,verbose=TRUE)
plot(recon)
plot_climateSpace(recon)
plot_scatterPDFs(recon,xlim=c(-25,30),ylim=c(0,2000),filename='FigureScatter',uncertainties = 0.5)
plot_violinPDFs(recon,filename='FigureViolin.png')
plot_taxaCharacteristics(recon,taxanames='Abies')
plot_low(recon)
plot_diagram(recon)
recon<-crest.reconstruct(recon,taxWeight='normalisation',presenceThreshold=0,verbose=TRUE)
plot(recon, climate = 'bio1')
plot(recon, climate = 'bio12')
plot(recon,simplify =FALSE)
plot_combinedPDFs(recon,samples=c(1),climate='bio1',only.present=TRUE,only.selected=FALSE)
plot_low(recon)
#Exportation des données
export(recon, dataname='final_reconGP_9Cas',fullUncertainties = FALSE,pdfs=FALSE)
